import { Container } from './components/container';
import { Footer } from './components/footer';
import { Header } from './components/header';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <meta
          name='viewport'
          content='width=device-width, height=device-height, initial-scale=1'
        />
      </head>
      <body>
        <div>
          <Header />
          <main className='bg-page-gradient pt-[var(--navigation-height)]'>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
