import { Container } from './components/container';
import { Header } from './components/header';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <div>
          <Header />
          <main className='pt-[var(--navigation-height)]'>{children}</main>
          <footer>
            <Container>footer</Container>
          </footer>
        </div>
      </body>
    </html>
  );
}
